2020/12/15 07:22:45 [error] 44#44: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.4, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.27.0.5:8001/service_health/", host: "kc.docker.internal"
2020/12/15 07:22:55 [error] 44#44: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.4, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.27.0.5:8001/service_health/", host: "kc.docker.internal"
2020/12/15 07:23:05 [error] 44#44: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.4, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.27.0.5:8001/service_health/", host: "kc.docker.internal"
2020/12/15 07:23:15 [error] 44#44: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.4, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.27.0.5:8001/service_health/", host: "kc.docker.internal"
2020/12/15 07:23:25 [error] 44#44: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.4, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.27.0.5:8001/service_health/", host: "kc.docker.internal"
2020/12/15 07:33:32 [error] 43#43: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.5, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.29.0.4:8001/service_health/", host: "kc.docker.internal"
2020/12/15 07:33:42 [error] 43#43: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.5, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.29.0.4:8001/service_health/", host: "kc.docker.internal"
2020/12/17 02:18:33 [error] 42#42: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.4, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://192.168.0.2:8001/service_health/", host: "kc.docker.internal"
2020/12/17 02:18:44 [error] 42#42: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.4, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://192.168.0.2:8001/service_health/", host: "kc.docker.internal"
2020/12/17 06:32:55 [error] 43#43: *112 open() "/srv/www/kobocat/img/apple-touch-icon.png" failed (2: No such file or directory), client: 191.106.165.170, server: kc.variamos.com, request: "GET /static/img/apple-touch-icon.png HTTP/1.1", host: "kc.variamos.com"
